import React from "react";

export const Photos = [
  "../images-2/img2.jpg",
  "../images-2/img5.jpg",
  "../images-2/img4.jpg",
  "../images-2/img6.jpg",
  "../images-2/img7.jpg",
  "../images-2/img8.jpg",
  "../images-2/img9.jpg",
  "../images-2/img10.jpg",
  "../images-2/img11.jpg",
  "../images-2/img12.jpg",
  "../images-2/img13.jpg",
  "../images-2/img14.png",
  "../images-2/img15.png",
  "../images-2/img16.jpg",
  "../images-2/img17.jpg",
  "../images-2/img18.jpg",
  "../images-2/img28.jpg",
  "../images-2/img19.jpg",
  "../images-2/img20.jpg",
  "../images-2/img1.jpg",
  "../images-2/img27.jpg",
  "../images-2/img21.jpg",
  "../images-2/img25.jpg",
  "../images-2/img22.jpg",
  "../images-2/img23.jpg",
  "../images-2/img24.jpg",
  "../images-2/img26.jpg",
];
